# provisioning/provision_malcolm.yml
- hosts: all
  become: true
  vars:
    malcolm_repo_url: "{{ apg_malcolm_repo_url | default('https://github.com/center-for-threat-informed-defense/malcolm') }}"
    malcolm_repo_revision: "{{ apg_malcolm_repo_revision | default('main') }}"
    docker_users: ["admin"]
    pcap_mount: /mnt/pcap
    opensearch_mount: /mnt/opensearch

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - git
          - jq
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repo
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker and containerd
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Ensure docker service running
      service:
        name: docker
        state: started
        enabled: true

    - name: Install docker compose plugin package (if available)
      apt:
        name: docker-compose-plugin
        state: present
      ignore_errors: yes

    - name: Add users to docker group
      user:
        name: "{{ item }}"
        groups: docker
        append: yes
      loop: "{{ docker_users }}"
      ignore_errors: yes

    - name: Create mountpoints for pcap and opensearch
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop:
        - "{{ pcap_mount }}"
        - "{{ opensearch_mount }}"

    - name: Detect unmounted block devices (simple heuristic)
      shell: |
        lsblk -J -o NAME,MOUNTPOINT,SIZE | jq -r '.blockdevices[] | select(.mountpoint==null) | .name' || true
      register: free_blockdevices
      changed_when: false

    - name: Debug block devices
      debug:
        var: free_blockdevices.stdout_lines

    - name: Clone Malcolm repo
      git:
        repo: "{{ malcolm_repo_url }}"
        dest: /opt/malcolm
        version: "{{ malcolm_repo_revision }}"
        force: yes
        accept_hostkey: yes

    - name: Write lab markers
      copy:
        dest: /var/lab_logs/malcolm_provisioned.txt
        content: |
          malcolm provisioned on {{ ansible_date_time.iso8601 }}
          malcolm_repo: {{ malcolm_repo_url }} @ {{ malcolm_repo_revision }}
        mode: '0644'

    - name: Write instructions file
      copy:
        dest: /var/lab_logs/malcolm_next_steps.txt
        content: |
          Malcolm repo klonet til /opt/malcolm.
          Neste steg (manuelt eller via ekstra playbook):
            - Formater/monter volumer under /mnt/pcap og /mnt/opensearch om nødvendig
            - cd /opt/malcolm && les README.md
            - Kjør 'docker compose up -d' eller repo spesifikk build-script
          Sørg for at VM har tilstrekkelig RAM og disk før oppstart!
        mode: '0644'
