- hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install tcpreplay and tcpdump
      apt:
        name:
          - tcpreplay
          - tcpdump
          - python3
          - python3-pip
        state: present

    - name: Create pcaps dir
      file:
        path: /opt/pcaps
        state: directory
        mode: '0755'

    - name: Copy sample pcap (from repo attacker_files/)
      copy:
        src: ../attacker_files/sample_attack.pcap
        dest: /opt/pcaps/sample_attack.pcap
        mode: '0644'
      ignore_errors: yes

    - name: Copy run_attack.sh
      copy:
        src: ../attacker_files/run_attack.sh
        dest: /usr/local/bin/run_attack.sh
        mode: '0755'

    - name: Create lab log directory
      file:
        path: /var/lab_logs
        state: directory
        mode: '0755'

    - name: Write attacker marker
      copy:
        dest: /var/lab_logs/attacker_provisioned.txt
        content: "attacker provisioned on {{ ansible_date_time.iso8601 }}"
        mode: '0644'
