# provisioning/provision_siem.yml
# Minimal SIEM provisioning:
# - update apt cache
# - install rsyslog (or minimal log collector)
# - install docker (optional) and grafana/loki placeholder comments
# This playbook aims to be minimal and idempotent per docs guidance.

- hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install minimal packages for log collection
      apt:
        name:
          - rsyslog
          - curl
          - apt-transport-https
          - ca-certificates
        state: present

    - name: Ensure rsyslog service is enabled and started
      service:
        name: rsyslog
        state: started
        enabled: true

    - name: Create directory for lab logs
      file:
        path: /var/lab_logs
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Drop example log for verification
      copy:
        dest: /var/lab_logs/siem_provisioned.txt
        content: "siem-host provisioned\n"
        owner: root
        mode: '0644'

    - name: (Optional) Placeholder - Configure Wazuh manager or Loki/Grafana
      debug:
        msg: "If you want Wazuh/Grafana/Loki, replace this debug task with installation tasks. Keep them idempotent."

# End of provision_siem.yml
